PRISM_ARGS=
PRISM=./prism
all: hw7

singleDie: singleDie.pm singleDie.pctl
	${PRISM} ${PRISM_ARGS} singleDie.pm singleDie.pctl

twoDice: twoDice.pm twoDice.pctl
	${PRISM} ${PRISM_ARGS} twoDice.pm twoDice.pctl

hw7: hw7-jmtappe.pm hw7-jmtappe.pctl
	${PRISM} ${PRISM_ARGS} hw7-jmtappe.pm hw7-jmtappe.pctl
